coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
    changes:
      default:
        informational: true

ignore:
  - "**/main.rs"
  - "**/examples"
  - "tasks"
  - "crates/oxc_ast/src/visit_mut.rs"
  - "crates/oxc_wasm" # Remove this once wasm is completed
  - "crates/oxc_parser/fuzz"
  - "crates/oxc_diagnostics"
  - "crates/oxc_type_synthesis"
