comment: false

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "tasks"
  - "crates/oxc_diagnostics"
  - "crates/oxc_ast/src/serialize.rs"
