[package]
name = "oxc_diagnostics"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
oxc_ast = { path = "../oxc_ast" }

thiserror = { workspace = true }
miette = { workspace = true }

unicode-width = "0.1.10"
owo-colors = { version = "3.5.0" }
textwrap = { version = "0.16.0" }
