[package]
name = "oxc_allocator"
version = "0.0.1"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bumpalo = { workspace = true, features = ["collections"] }
serde = { workspace = true }
