# Run `cargo-unused-features` for finding out unused features

name: Cargo Unused Features

on:
  workflow_dispatch:

env:
  CARGO_TERM_QUIET: true

jobs:
  bloat:
    name: Cargo Unused Features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        run: rustup show

      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install cargo-unused-features
        run: cargo binstall cargo-unused-features -y

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run
        run: unused-features analyze
